### ISSUE TITLE
Dependency on VTK is not listed but still tested by default

### ISSUE THREAD

**Issue by revesansparole** [VirtualPlants/cellcomplex#1]
I tried to run all the tests with nosetests and I get a complain that VTK is not installed:
Traceback (most recent call last):
  File "/home/tempo/miniconda2/envs/draco/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tempo/Documents/cellcomplex/test/test_topomesh_geometrical_properties.py", line 106, in test_curvature_property
    topomesh = vtk_ellipsoid_topomesh(ellipsoid_radius=radius)
  File "/home/tempo/Documents/cellcomplex/src/openalea/cellcomplex/property_topomesh/example_topomesh.py", line 48, in vtk_ellipsoid_topomesh
    import vtk
ImportError: No module named vtk

Cheers,

Jérôme

**Comment by gcerutti** [comment]
True, i use vtk to generate an example data.

What would be the best practice, run the test only if vtk is available, or load the example data from a file (making the test a bit less "unitary")? 

...Or make vtk an explicit dependency (which it is not for the core functionalities of the package)?
